baseURL = ""
languageCode = "ja-JP"
title = "CloudNative Days"
theme = "hugograyscale"

publishDir = "docs"

[params]
    customCSS = ["css/custom.css"]
    images = ["https://cloudnativedays.jp/img/cndtop.jpg"]
    