name: pull request

on:
  pull_request:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: rtakaishi/hugo-aws
    steps:
    - uses: actions/checkout@master

    - name: install
      run: hugo

    - name: Comment succeeded
      uses: mshick/add-pr-comment@v1
      if: success()
      with:
        message: |
          Build succeeded!
          Visit https://cloudnativedaysjp-website.s3-ap-northeast-1.amazonaws.com/index.html
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment failed
      uses: mshick/add-pr-comment@v1
      if: failure()
      with:
        message: "Build failed😗"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
