name: pull request

on:
  pull_request:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Checkout submodules
      shell: bash
      run: |
        git submodule sync --recursive

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.64.0'

    - name: Build
      run: |
        ls -la theme
        hugo
        ls -la docs/

    - name: Publish to AWS S3
      uses: opspresso/action-s3-sync@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "ap-northeast-1"
        CF_RESET: false
        FROM_PATH: "./docs"
        DEST_PATH: "s3://cloudnativedaysjp-website/"
        OPTIONS: "--acl public-read --delete"

    - name: Comment succeeded
      uses: mshick/add-pr-comment@v1
      if: success()
      with:
        message: |
          Build succeeded!
          Visit https://cloudnativedaysjp-website.s3-ap-northeast-1.amazonaws.com/index.html
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment failed
      uses: mshick/add-pr-comment@v1
      if: failure()
      with:
        message: "Build failed😗"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
